#!/bin/sh /etc/rc.common
DAEMON=/root/app_info
DAEMON_OPTS="c"

#exec >>/root/rclone.log 2>&1

START=99

start ()
{
        echo " Starting main-app"
        #start-stop-daemon -S -o --background -x $DAEMON -- $DAEMON_OPTS
        start-stop-daemon -S -b -x $DAEMON -- $DAEMON_OPTS
}
stop ()
{
        echo " Stoping main-app"
        start-stop-daemon -K -x $DAEMON
}
restart()
{
        stop
        start
}
